services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=hacaton.settings
    command: python manage.py runserver 0.0.0.0:8000

networks:
  hacaton_network:
    driver: bridge